version: 2.1

jobs:
  mvn-build:
    docker:
      - image: circleci/openjdk:stretch
    working_directory: ~/petclinic-rest/docker
    steps:
      - checkout:
          path: ~/petclinic-rest
      - run: 
          name: Build maven jar
          command: |
            mvn clean install
      - persist_to_workspace:
          root: ~/petclinic-rest
          paths:
            - docker
            - helm-rest

  docker-build-push:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/petclinic-rest/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - attach_workspace:
          at: ~/petclinic-rest
      - run:
          name: Build & push docker image
          command: |
            docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            docker build -t ${DOCKER_USERNAME}/petclinic-rest:${CIRCLE_SHA1} .
            docker push ${DOCKER_USERNAME}/petclinic-rest:${CIRCLE_SHA1}
      - persist_to_workspace:
          root: ~/petclinic-rest
          paths:
            - helm-rest
  deploy:
    docker:
      - image: jshimko/kube-tools-aws
    working_directory:  ~/petclinic-rest/helm-rest
    steps:
      - attach_workspace:
          at: ~/petclinic-rest
      - run:
          name: Import kubeconfig
          command: |
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET__KEY}
            aws eks --region ${AWS_REGION} update-kubeconfig --name ${EKS_CLUSTER_NAME}
      - run:
          name: Deploy into eks
          command: |
            sed -i -e "s/latest/${CIRCLE_SHA1}/g" values.yaml 
            helm install petclinic-rest helm-rest
           
workflows:
  mvn & docker build:
    jobs:
      - mvn-build
      - docker-build-push:
          requires:
            - mvn-build
      - deploy:
          requires:
            - docker-build-push
