apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petclinic-rest.fullname" . }}
  labels:
    app: {{ include "petclinic-rest.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "petclinic-rest.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "petclinic-rest.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.containerport }}
        envFrom:
        - configMapRef:
            name: {{ include "petclinic-rest.fullname" . }}