replicaCount: 1

image:
  repository: manvitha9630/petclinic-rest
  tag: "latest"

service:
  type: LoadBalancer
  containerport: 9966
  port: 9966

configmap:
  spring_datasource_url: jdbc:postgresql://petclinic.c61anvbt5ndd.us-east-1.rds.amazonaws.com:5432/petclinic

